### PR TITLE
fix: switch to 3d

### LINKED ISSUE #756: Not possible to switch to 3D maps
**Describe the bug**
When visiting the map viewer, it's not possible to switch to 3D if there are no 2D maps.

**To reproduce**
- Navigate to Explore
- Select Zebrafish and Map Viewer
- Try to switch to 3D

**Expected behavior**
3D should be the default if there are no 2D maps. The 2D map button should be disabled.

**Additional context**
See comments [here](https://github.com/MetabolicAtlas/MetabolicAtlas/pull/746#issuecomment-963329101).

### PR DESCRIPTION
**Pull request by MalinAhlberg**
**Related issue(s) and PR(s)**  
This PR closes #756 

Solves the issue of not being able to switch to 3D maps when there are no 2D maps, or when you end up on an invalid map page (eg `/explore/Fruitfly-GEM/map-viewer/phenylalanine_tyrosine_and_tryptophan_biosynthesisxxx?dim=2d`).

**Type of change**  

- [X] Bug fix (non-breaking change which fixes an issue)

 
**List of changes made**  
1. adds a state that keeps track of whether there are available 2D maps
2. defaults to 3D when there are no 2D maps
3. disables the switch buttons when there are no 2D maps
4. allows switching to 3D when visiting a non-existing 2D map
5. allows switching to 3D before choosing map.

**Testing**  
- To test 5:
    - go to `https://metabolicatlas.org/explore/Human-GEM/map-viewer?dim=2d`. Clicking `Switch to 3D` will not do anything
    - on this branch `/explore/Human-GEM/map-viewer?dim=2d`, clicking the same button will refresh the list of available maps
- To test 4, visit `/explore/Fruitfly-GEM/map-viewer/phenylalanine_tyrosine_and_tryptophan_biosynthesisxxx?dim=2d` and change to 3D.
- To test 2&3: visit the Map Viewer for Fruitfly.

**Further comments**  
I'm not very sure about the general design of the state and related functions. 

**Checklist**  

- [X] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings

### CODE REVIEW

File: frontend/src/store/modules/maps.js [hunk 1]
```diff
@@ -52,9 +53,15 @@ const getters = {
 };
 
 const actions = {
+
   async getMapsListing({ commit }, model) {
     const payload = { model: model.apiName, version: model.apiVersion };
     const mapsListing = await mapsApi.fetchMapsListing(payload);
+    let avail2D = false;
+    Object.keys(mapsListing).forEach((cat) => {
+      avail2D = mapsListing[cat].some(x => x.svgs.length === 1) || avail2D;
```
Comment (inghylt) [inline frontend/src/store/modules/maps.js:62]: I wonder if it makes sense to have `x.svgs.length > 0` since Cytosol has multiple svg:s. But I don't think any model has only Cytosol as 2d map so this should also be fine

File: frontend/src/store/modules/maps.js [hunk 2]
```diff
@@ -52,9 +53,15 @@ const getters = {
 };
 
 const actions = {
+
   async getMapsListing({ commit }, model) {
     const payload = { model: model.apiName, version: model.apiVersion };
     const mapsListing = await mapsApi.fetchMapsListing(payload);
+    let avail2D = false;
+    Object.keys(mapsListing).forEach((cat) => {
```
Comment (inghylt) [inline frontend/src/store/modules/maps.js:61]: Out of curiosity, why `cat`?

**Comment by inghylt** [comment]
Nice work! :clap:

I think it makes sense to disable the button switch between 2D and 3D for models without any 2D maps. However, I think it might be nice to make the text displayed when hovering the button explain why it is disabled, maybe something like "This model only have 3D maps available" or something

image

File: frontend/src/store/modules/maps.js (hunk 1 above)
Comment (e0) [reply frontend/src/store/modules/maps.js:62]: I think this is a good suggestion. I'm also wondering if we can short-circuit the iteration so we don't have to go through every item. Maybe something like the following. 

```javascript
    // eslint-disable-next-line
    for (const { svgs } of Object.values(mapsListing).flat()) {
      if (svgs.length > 0) {
        avail2D = true;
        break;
      }
    }
```

Please note that I'm not actually sure if this is faster.. both ways are probably fast enough to have any noticeable effect but this makes more sense to me logically.

**Review by e0 — APPROVED** [review]
This looks great! Really nice way of setting it to 3D when svgs aren't available.

File: frontend/src/store/modules/maps.js (hunk 2 above)
Comment (MalinAhlberg) [reply frontend/src/store/modules/maps.js:61]: I was thinking `category`, the `mapListing` has the keys `compartment maps`, `subsystem maps` etc (but now I had to think for some minutes before remembering why I called it `cat`, so maybe it's not a very good name after all... If you have better suggestions, please let me know :))

File: frontend/src/store/modules/maps.js (hunk 1 above)
Comment (MalinAhlberg) [reply frontend/src/store/modules/maps.js:62]: Thanks for the suggestions :)

I more or less copied the `svgs.length === 1` from `MapListings.vue` and didn't dare to change it. But yes, `> 0` sounds better!

I also think that your idea makes much sense @e0. Do you prefer the `for` loop, even though `eslint` gets upset about it?

**Review by nanjiangshu — COMMENTED** [review]
Really nice fix @MalinAhlberg. I agree with @inghylt that it will be good to add a notification to explain why it is not able to switch to 2D, either in the hover text, e.g. "2D map not available, switch to 2D disabled", or similar pop up text when the users click on the map switching region. However, if you think this is out of scope of this issue. I can also accept it as it is.

**Comment by MalinAhlberg** [comment]
> I think it makes sense to disable the button switch between 2D and 3D for models without any 2D maps. However, I think it might be nice to make the text displayed when hovering the button explain why it is disabled, maybe something like "This model only have 3D maps available" or something
> 
> image

Good idea! Added in a5c6719e24c7639dafed0d5c7b4a7304b9ec56c7

File: frontend/src/store/modules/maps.js (hunk 1 above)
Comment (MalinAhlberg) [reply frontend/src/store/modules/maps.js]: Updated to the suggestion above in 26a2acc62d9759498d19a333708c528a05ed8baa

Comment (e0) [reply frontend/src/store/modules/maps.js]: Sorry for the slow response @MalinAhlberg. Good that you thought about the `eslint` warning. It's not ideal but I looked up how to [short-circuit a `forEach`](https://stackoverflow.com/a/2641374) and thought this was the better alternative.

There is also another variant using `every` (it immediately returns when a falsy value is returned in the iterator but I still think the `for` loop is more readable.

```javascript
    Object.values(mapsListing).flat().every(({ svgs }) => {
      if (svgs.length > 0) {
        avail2D = true;
        return false;
      }
      return true;
    });
```

File: frontend/src/components/explorer/MapViewer.vue [hunk 3]
```diff
@@ -156,6 +158,12 @@ export default {
     queryParams() {
       return { ...this.mapQueryParams, ...this.dataOverlayQueryParams };
     },
+    switchTitle() {
+      if (this.avail2D) {
+        return `Switch to ${this.dimensionalState(!this.showing2D)}`;
+      }
+      return 'This model only has 3D maps availabe';
```
Comment (inghylt) [inline frontend/src/components/explorer/MapViewer.vue:165]:
```suggestion
      return 'This model only has 3D maps available';
```

Another alternative could be "There are only 3D maps available for this model"

Comment (MalinAhlberg) [reply frontend/src/components/explorer/MapViewer.vue]: :grimacing: oops.

File: frontend/src/store/modules/maps.js (hunk 1 above)
Comment (MalinAhlberg) [reply frontend/src/store/modules/maps.js]: Thanks for the link and examples!! Using `every` is tempting, I had to try out the one-line-version. But it got very unreadable, especially with the negated truth value checking :smile:
```js
    avail2D = ! Object.values(mapsListing).flat().every(function(map) {return map.svgs.length === 0});
```

Comment (e0) [reply frontend/src/store/modules/maps.js]: That looks pretty good I think! I guess you can make this slightly shorter with using an arrow function and knowing that `0` is a falsy value in JavaScript.

```javascript
    avail2D = !Object.values(mapsListing).flat().every((m) => m.svgs.length);
```

**Review by nanjiangshu — APPROVED** [review]
Very nice with added information when switching is disabled

File: frontend/src/store/modules/maps.js (hunk 1 above)
Comment (MalinAhlberg) [reply frontend/src/store/modules/maps.js]: Aha, nice :star: !!! Maybe not very readable for random humans, but indeed nice.

> Edit: On second thought, this might not work as intended. If the first compartment map does not have any SVGs but the other maps have, then this gives the wrong result right?

Since it flattened, that shouldn't be a problem?

Comment (e0) [reply frontend/src/store/modules/maps.js]: I meant my follow up suggestion, since it only looks at the length and doesn't check if it is equal to 0, it would be the inverse or your original one-liner.

Comment (MalinAhlberg) [reply frontend/src/store/modules/maps.js]: Ah, I see, good point. So `m.svgs` would be null(-ish) and hence falsy?
But then it would have to be like this
```js
    avail2D = !Object.values(mapsListing).flat().every((m) => m.svgs.length === 0);

```
Still nice!

File: frontend/src/components/explorer/MapViewer.vue [hunk 4]
```diff
@@ -156,6 +158,12 @@ export default {
     queryParams() {
       return { ...this.mapQueryParams, ...this.dataOverlayQueryParams };
     },
+    switchTitle() {
```
[the remark this answers is not in the document]
Comment (MalinAhlberg) [reply frontend/src/components/explorer/MapViewer.vue:161]: That's the actual title on the switch button, which is always "Switch to 2D / 3D". Do you think that should be changed to? In that case  'This model only has 3D maps available' might be a bit too long.

[the remark this answers is not in the document]
Comment (e0) [reply frontend/src/components/explorer/MapViewer.vue:161]: > That's the actual title on the switch button, which is always "Switch to 2D / 3D". Do you think that should be changed to? In that case  'This model only has 3D maps available' might be a bit too long.

Want to chime in and say the button itself should not be modified imo. The tooltip change is great though. So I support the way things are now.

[the remark this answers is not in the document]
Comment (inghylt) [reply frontend/src/components/explorer/MapViewer.vue:161]: Aah sorry my bad, yes makes sense to keep things as they are :+1:

File: frontend/src/store/modules/maps.js (hunk 1 above)
Comment (mihai-sysbio) [reply frontend/src/store/modules/maps.js]: Random idea: instead of passing on this computation to the client browser, would it make sense to have it in the API response?

File: frontend/src/store/modules/maps.js (hunk 2 above)
Comment (mihai-sysbio) [reply frontend/src/store/modules/maps.js]: `componentWithMap`?

**Review by inghylt — APPROVED** [review]
Nice work!

File: frontend/src/components/explorer/MapViewer.vue [hunk 5]
```diff
@@ -156,6 +158,12 @@ export default {
...
+      if (this.avail2D) {
+        return `Switch to ${this.dimensionalState(!this.showing2D)}`;
+      }
+      return 'This model only has 3D maps available';
```
Comment (mihai-sysbio) [inline frontend/src/components/explorer/MapViewer.vue:165]: Maybe this sounds clearer?
```suggestion
      return 'This model has only 3D maps available';
```

File: frontend/src/store/modules/maps.js (hunk 1 above)
Comment (MalinAhlberg) [reply frontend/src/store/modules/maps.js]: I think it's a very reasonable idea, but I'm not sure it's worth the refactoring? It's not a heavy computation. But I'm up for changing if there is an agreement that we should do so :)

Comment (e0) [reply frontend/src/store/modules/maps.js]: > Random idea: instead of passing on this computation to the client browser, would it make sense to have it in the API response?

Interesting suggestion but I would not do this for the following reasons.

1. The performance difference is near-zero considering all the other intensive things that the frontend must handle such as rendering the maps.
2. This serves a very frontend specific purpose. IMO the data returned from the backend should be as flexible as possible so that the data is cleaner for API users.

File: frontend/src/components/explorer/MapViewer.vue (hunk 5 above)
Comment (mihai-sysbio) [reply frontend/src/components/explorer/MapViewer.vue:165]: Fixed in another PR #794 .
