### PR TITLE
fix: improve ec search

### LINKED ISSUE #1060: cannot search for some EC codes in GotEnzymes
**Describe the bug**

When searching for some valid EC codes, they don't show up as suggestion so it appears they are missing, even if they are not.

**Steps to reproduce**

Navigate to the landing page of GotEnzymes and search for a valid EC code such as `7.1.1.1`.

**Expected behavior**

- [ ] when searching for a valid EC code, the first search suggestion should be that EC code

**Screenshots**

**Additional context**

It might have to do with the `.` being removed by the API or Postgres itself, since it is not removed by the frontend.

### PR DESCRIPTION
**Pull request by MalinAhlberg**
**Related issue(s) and PR(s)**  
This PR closes #1060. Joint work with @e0.

The `.` in the EC codes are replaced by a standard character (`a`) in the psql search, so that the standard similarity score works as expected.

**Type of change**  

- [X] Bug fix (non-breaking change which fixes an issue)

**List of changes made**  

- Use replacement of special character to improve search results for ECs.

**Screenshot of the fix**  

2022-08-10-174151_973x509_scrot

**Testing**  

- Try searching for example `7.1.1.1` and make sure the first hit is the exact match
- Search for `1.1.3` and see that the results are relevant
- Also try other types of searches to make sure the work as expected and that performance is not affected.

**Definition of Done checklist**  
- [X] My code meets the Acceptance Criteria
- [X] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [X] I have performed a self-review of my own code and commented any hard-to-understand areas
- [X] Tests and lint/format validations are passing
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by e0** [comment]
When checking both the dev server and locally, it seems that searching for `7.1.1.1` does show up but it may not be ranked first. This is due to the fact that they all get the `similarity` score of `1`.

image

Following is what I see from the dev server. As you see it is listed as the 4th item.

image

So I think we probably do not need to add an extra query to search for `ec`. We could add some custom logic to move the exact match to first in the list and that can be done in JavaScript after all the calls are made I think.

**Comment by mihai-sysbio** [comment]
> This is due to the fact that they all get the `similarity` score of `1`.

Isn't that a bit frustrating though? `7.1.1.1` is an _exact_ match, whereas `1.7.1.1` is not. 

For some  ec codes, the exact match might not even be listed: 
image

**Comment by e0** [comment]
> Isn't that a bit frustrating though? `7.1.1.1` is an _exact_ match, whereas `1.7.1.1` is not.

> For some ec codes, the exact match might not even be listed:

Frustrating indeed. Especially if there is possibility of the exact match not showing in the top 10, which requires further action.

Ideally we would want to see if there is a solution for configuring the fuzzy search to be order sensitive so that when searching for `123`, `123` gets a better score than `231`.

The fast solution (without further research) is to modify the `ecMatchQuery` in this PR to be more similar to the `geneMatchQuery`. So that we look for a perfect match instead. Then we need to manually remove duplicates (if any) before slicing out the top 10 results.

**Comment by MalinAhlberg** [comment]
Thanks for the input @e0 and @mihai-sysbio!
It's a very valid idea to reorder the results in js! Though personally I do appreciate that the result, when searching for eg `7.1.1.`, contains all ids that starts with that exact string, as in my first picture. If that's something we want, I think doing the extra db search for prefixes makes sense. Doing the search for an exact match would in my opinion be a bit frustrating for the user, since you need to type so much. But I'm not a real user of this, so I'm very open for other ideas.

**Comment by e0** [comment]
> It's a very valid idea to reorder the results in js! Though personally I do appreciate that the result, when searching for eg `7.1.1.`, contains all ids that starts with that exact string, as in my first picture.

That's a really good point @MalinAhlberg! I think the new `ecMatchQuery ` is superior in some cases while worse in others. For example it seems to work well for `7.1.1.`. Results below `ecMatchQuery` first, then `multi_search`.

image
image

However if we search for `7.1.11`, we get the following instead. Results below `ecMatchQuery` first, then `multi_search`.

image
image

I think it's worth testing both a bit more and see what the best way to combine them is.

**Comment by MalinAhlberg** [comment]
Interesting @e0! That's a very good point! Let's continue the investigation :)

**Comment by mihai-sysbio** [comment]
I'm adding here another test case `3.1.3.-` is not listing the match. My suspicion is that somehow non-letters have practically no weight in the fuzzy matching.

**Comment by MalinAhlberg** [comment]
> I'm adding here another test case: `3.1.3.-` is not listing the match. My suspicion is that somehow non-letters have practically no weight in the fuzzy matching.



Is there a match for that exact ec? I can't find it at `gotenzymes/ec/3.1.3.-` either?

**Comment by mihai-sysbio** [comment]
> Is there a match for that exact ec? I can't find it at `gotenzymes/ec/3.1.3.-` either?

That's a (different) bug then:
image

**Comment by e0** [comment]
I think that's a known issue from before. There is no such entry in the `ec` table.

image

**Comment by e0** [comment]
I did some more reading and experimenting on this. It turns out that the reason for this case is quite simple as `pg_trgrm` is meant to work with alphanumerical characters. So I thought in the `similarity` function, maybe we can replace the `.` with an accepted character, for example the following:

```sql
  const fuzzyQuery = sql`
    select
      type,
      id,
      match,
      ${sql`similarity(
        ${sql`replace(match, '.', 'a')`},
        ${sql`replace(${term}, '.', 'a')`}
      )`} as score
    from multi_search
    where match % ${term}
    order by score desc
    limit 10
  `;
```

Here is an example of this when run.

image

This looks pretty promising and maybe we can do some more tests on this and see how it behaves.

**Comment by e0** [comment]
> That's an interesting approach, @e0! Does it also work for `-`, as in `3.1.3.-`?

In theory we could replace that too. At the moment we don't have these entries with `-` in the `ec` table. They are only found in the `enzymes` table, which we are not using in `multi_search`.

**Comment by MalinAhlberg** [comment]
I just tested your latest verison @e0 and I think it behaves really nice, almost always. There are some cases that are a bit weird, like this
2022-08-10-154840_728x497_scrot
where you might expect more hits starting with `1.9` being ranked higher.

All in all, I think it's a really nice approach though, as we don't need extra searching or reordering.

**Comment by e0** [comment]
That sounds good @MalinAhlberg and I have similar sentiment after testing! 

This is an interesting example and looking at the results it kind of makes sense. I guess I can understand how the algorithm thinks `1.1.1.9` is most similar to `1.9`.

image

I think this is still a small improvement over what's currently on the dev server now. For example it includes `1.1.5.9`, which does not have the exact sequence of `1.9`.

image

Would you like to commit the changes and un-draft the PR?

**Review by e0 — APPROVED** [review]
LGTM! Already tested this rather extensively so will just approve it now.

File: api/src/gotEnzymes/search.js [hunk 1]
```diff
@@ -3,7 +3,14 @@ import sql from 'gotEnzymes/db';
...
   const term = searchTerm.toLowerCase();
   const fuzzyQuery = sql`
-    select type, id, match, ${sql`similarity(match, ${term})`} as score
+    select
+      type,
+      id,
+      match,
+      ${sql`similarity(
+        ${sql`replace(match, '.', 'a')`},
+        ${sql`replace(${term}, '.', 'a')`}
```
Comment (mihai-sysbio) [inline api/src/gotEnzymes/search.js:12]: I'm wondering if where this replacement is best done, i.e. would it be better if done in the `frontend` or the `api`, rather than the `pg` container?

Comment (inghylt) [reply api/src/gotEnzymes/search.js:12]: I have no problem of keeping it here. It gives a strong connection between the replacement and where it is actually used

**Review by inghylt — APPROVED** [review]
Have tested searching for different ec codes and other components and everything seems fine, good job :+1:

File: api/src/gotEnzymes/search.js (hunk 1 above)
Comment (nanjiangshu) [reply api/src/gotEnzymes/search.js:12]: I also think it's good to place the replacement here. I was a bit confused by the commit message at the beginning though. Sounds like the search term after replacement is used in sql querying but actually the modified strings are used for similarity calculation.

**Review by nanjiangshu — APPROVED** [review]
Great fix and very smart way to solve the scoring problem!
