### PR TITLE
fix: make consistent url when switching between 2D/3D Map Viewer for SVG maps with sub maps 

### LINKED ISSUE #745: Inconsistent and sometimes nonfunctional url for Cytosol
**Describe the bug**
The url when moving between 2D and 3D map(s) for Cytosol, the url is not consistent, which can lead to broken map viewer functionality

**To reproduce**
1. Visit `/explore/Human-GEM/gem-browser/reaction/MAR10743`
2. Press Cytosol 3D
3. Note that the url is `/explore/Human-GEM/map-viewer/cytosol?dim=3d`
4. Press 2D
5. Note that the url is `/explore/Human-GEM/map-viewer/cytosol?dim=2d` (seems like it is Cytosol_4 showing)
6. Reload the current page (Ctrl-r)
7. Note that you can't click on 3D
8. Now visit `/explore/Human-GEM/gem-browser/reaction/MAR10743` again
9. Press 2D Part 1
10. Note that the url is `explore/Human-GEM/map-viewer/cytosol_1?dim=2d`
11. Press 3D
12. Note that the url is `explore/Human-GEM/map-viewer/cytosol_1?dim=3d`

**Expected behavior**
That users can go from either 3D to 2D and vice versa and that the url reflect the current page and does not lead to broken map virw

**Screenshots**

### PR DESCRIPTION
**Pull request by nanjiangshu**
**Related issue(s) and PR(s)**  
This PR closes #745 

The URL in the address bar is reset to reflect the actual map shows in the Map Viewer, so that a hard refresh (ctrl-r) will not show `map not found` error
**Type of change**  

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other
 
**List of changes made**  

**Screenshot of the fix**  

**Testing**  

- Instructions on how to test
Follow the steps described in the issue  #745, the buggy behavior will disappear. 
Moreover, when switching to the 2D map viewer, select e.g. `Part 4`, and then switch to 3D and then switch back to 2D, the original 2D map for `Part 4` will be restored.  

**Further comments**  

When switching to the 2D map for the first time from the 3D map viewer, the SVG map `Part 2`, which is the first element of the array `this.currentMap.svgs`,  is selected. This might be discussed if it is reasonable. 

**Checklist**  

- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

File: frontend/src/components/explorer/MapViewer.vue [hunk 1]
```diff
@@ -277,10 +277,20 @@ export default {
       const queryString = Object.entries(newQuery)
         .map(e => e.join('='))
         .join('&');
-      const payload = [{}, null, `${this.$route.path}?${queryString}`];
+
       if (newQuery.dim === this.$route.query.dim || (newQuery.dim && !this.$route.query.dim)) {
+        const payload = [{}, null, `${this.$route.path}?${queryString}`];
         history.replaceState(...payload); // eslint-disable-line no-restricted-globals
       } else {
+        let urlPath = `${this.$route.path}`;
```
Comment (MalinAhlberg) [inline frontend/src/components/explorer/MapViewer.vue:285]: To avoid future confusion, I think a comment about what's going on would be nice here

**Review by MalinAhlberg — APPROVED** [review]
Seems to work very well :+1: !

I left a comment about comments. Apart from that, I approve!

File: frontend/src/components/explorer/MapViewer.vue (hunk 1 above)
Comment (nanjiangshu) [reply frontend/src/components/explorer/MapViewer.vue:286]: Thanks for the comment! I've added some explanation to the code in the commit 3722c94

However, I'm not quite sure to which extent the code should be commented. If you go through the code for MetAtlas, there are very little comment. It's great that you raised this question and I think we should discuss about this: whether and how should we add comment in the code.

Comment (MalinAhlberg) [reply frontend/src/components/explorer/MapViewer.vue:286]: Thanks! And yes, I have noticed the lack of comments :). I think at least adding very short comments would help in many places, the code base is quite massive and it's sometimes hard to figure out what's going on. But there are of course drawbacks of comments, such as the risk of them not being updated when the code is, etc. So es, a discussion would be good!

**Review by e0 — APPROVED** [review]
