### PR TITLE
fix: clean search term and escape bad characters for neo4j

### LINKED ISSUE #764: Quick search throws error when using charachter :
**Describe the bug**

Using quick search and typing in `:` leads to an error

**Steps to reproduce**

Type for example `gene:` in quick search, note the error being reported

**Expected behavior**

That no error is reported but that the quick search works as normally

**Screenshots**

### PR DESCRIPTION
**Pull request by nanjiangshu**
**Related issue(s) and PR(s)**  
This PR closes #764 and (probably) #884

**Type of change**  

- [x] Bug fix (non-breaking change which fixes an issue)
 
**List of changes made**  

The search term for the quick search is cleaned to avoid unexpected neo4j querying error.
1. Special characters are escaped by adding `\ `
2. The character `"` and `\` are removed since it may cause errors even after escaping- 
3. Multiple white spaces are replaced with a single space
4. the trailing white spaces are removed 

Besides, a test is added for searching of terms with special characters.

**Screenshot of the fix**  

**Testing**  

- Instructions on how to test
Test in the quick search with searching terms e.g.  
1. `Node: rna`, 
2. `Tricarboxylic acid cycle and glyoxylate/dicarboxylate ` 
3. `°!#€€#€%&&///(/(())())=?``^ÅPOIUUYYTTRRE EWW_:;M:*ÄÖ*^ÄÖLKK;:;M_:;>ZXZXCVV°!"©@££$∞§ ∞§|[]]≈± ø–‘›‹ç≈÷≈çç‹›‘›‘ ‘’ ’ –ßß∂ƒƒ¸ ƒ¸˛˛√√ªﬁøæıüµ•Ωé®†µµüıı©@£$∞§§§||[ []] []≈±´`  😄  

**Further comments**  

**Checklist**  

- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have checked so that the same data as before is returned by the API

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
It sounds like this would also partly resolve #856 - if so, maybe we should refine that issue.

**Comment by nanjiangshu** [comment]
Thanks @mihai-sysbio for pointing out the problem with backslash in the search term. A fix has been added in the commit 17c7f4e8

**Comment by e0** [comment]
> Thanks @mihai-sysbio for pointing out the problem with backslash in the search term. A fix has been added in the commit [17c7f4e](https://github.com/MetabolicAtlas/MetabolicAtlas/commit/17c7f4e89e10d820bda181d943ff5b7f21540f9e)

Works well from what I tested but the backslash escaping problem still seems unsolved.

**Comment by nanjiangshu** [comment]
> > Thanks @mihai-sysbio for pointing out the problem with backslash in the search term. A fix has been added in the commit [17c7f4e](https://github.com/MetabolicAtlas/MetabolicAtlas/commit/17c7f4e89e10d820bda181d943ff5b7f21540f9e)
> 
> Works well from what I tested but the backslash escaping problem still seems unsolved.

Hi @e0 Thanks for testing. Could you please share the search term you used? I tested various terms with backslashes, such as `\\ askd\( \[\\// \\'"\"2\\\'.*///\/\/`, `!\/\(\\//`, but the error message is not prompted.

**Comment by e0** [comment]
> > > Thanks @mihai-sysbio for pointing out the problem with backslash in the search term. A fix has been added in the commit [17c7f4e](https://github.com/MetabolicAtlas/MetabolicAtlas/commit/17c7f4e89e10d820bda181d943ff5b7f21540f9e)
> > 
> > 
> > Works well from what I tested but the backslash escaping problem still seems unsolved.
> 
> Hi @e0 Thanks for testing. Could you please share the search term you used? I tested various terms with backslashes, such as `\\ askd\( \[\\// \\'"\"2\\\'.*///\/\/`, `!\/\(\\//`, but the error message is not prompted.

The searches worked fine actually. It's just about the CodeQL thing: https://github.com/MetabolicAtlas/MetabolicAtlas/security/code-scanning/28?query=ref%3Arefs%2Fpull%2F880%2Fmerge+ref%3Arefs%2Fpull%2F880%2Fhead+ref%3Arefs%2Fheads%2Ffix%2Fquick-search-error-chars

**Comment by nanjiangshu** [comment]
```javascript
  term = term
    .replace(/\s\s+/g, ' ')
    .replace(/^\s|\s$/g, '')
    .replace(/([\"\\])/g, '')
    .replace(/([:/^!\"\(\)\[\]])/g, '\\$1');
```
> This does not escape backslash characters in the input. CodeQL

I don't quite understand the warning made by CodeQL. Firstly, it does not make any warning previously when there is no sanitizing at all.  Secondly, the third `replace()` in the code removes all backslashes from the original search term, and then the fourth search term adds backslashes if we still want to parse special characters such as `(`, `'` to the neo4j query. CodeQL says `This does not escape backslash characters in the input`, is this because of the addition of backslashes in the fouth replace(). I'm not sure of removal of all the special characters will undo this CodeQL warning. Some characters like `!` might be removed, but we probably need to keep characters such as `(` and `:`?

**Comment by e0** [comment]
> I don't quite understand the warning made by CodeQL. Firstly, it does not make any warning previously when there is no sanitizing at all.  Secondly, the third replace() in the code removes all backslashes from the original search term, and then the fourth search term adds backslashes if we still want to parse special characters such as (, ' to the neo4j query. CodeQL says This does not escape backslash characters in the input, is this because of the addition of backslashes in the fouth replace(). I'm not sure of removal of all the special characters will undo this CodeQL warning. Some characters like ! might be removed, but we probably need to keep characters such as ( and :?

I tested this a bit more and see that the search breaks if you type in `\\\`. Trying this in the browser JavaScript console confirms the error. In the linked page from my previous comment, they have some good advice if you click "Show more".

image

**Comment by nanjiangshu** [comment]
Hi @e0 , thanks for pointing out that the search string `\\\` caused the error message. This is because backslashes are removed and thus results in an empty search string, but the minimal length checking is still passed since it is checking the length of the original input string. I have moved the sanitizing function from the `api` to the `frontend` and the minimal length checking is for the sanitized string. In addition, the CodeQL warning is also solved with a more complete regexp. 

There are still room for improvement. For example, the maximum length of input is not restricted. But I think this is a more general problem but limited to the GemSearch, so it is better to be solved in https://app.zenhub.com/workspaces/metatlas-sprint-607745622d49260019ce115a/issues/metabolicatlas/metabolicatlas/856.

File: api/src/neo4j/queries/search.js [hunk 1]
```diff
@@ -326,7 +326,7 @@ const _search = async ({
 
   // the EC field for reaction could contain ":", which is a special character
   // in this case th search term is modified to be escape and perform an exact match
```
Comment (inghylt) [inline api/src/neo4j/queries/search.js:328]:
```suggestion
  // in this case the search term is modified to be escaped and perform an exact match
```

**Review by inghylt — COMMENTED** [review]
I think the changes look good! Two things though:

- The highlighting of matching text in result seems to be affected. Compare searching for `MAR10368` on localhost and metabolicatlas.org. It's not completely broken though, for example when searching for `Glycosylphosphatidylinositol (GPI)-anchor` you get highlighted text as expected

- Seems like you get some kind of result for all search terms except variants of just using `\\`, then it just keeps on loading (see image below). Not sure if this is something we should care about though since users probably won't be affected negatively by this.
image

**Comment by nanjiangshu** [comment]
Thanks for reviewing @inghylt 
> I think the changes look good! Two things though:
> 
>     * The highlighting of matching text in result seems to be affected. Compare searching for `MAR10368` on localhost and metabolicatlas.org. It's not completely broken though, for example when searching for `Glycosylphosphatidylinositol (GPI)-anchor` you get highlighted text as expected
> 
Interesting. I do see highlight when searching for the key word `MAR10368` as seen in the screenshot below.
Screenshot 2022-02-18 at 11 38 27


>     * Seems like you get some kind of result for all search terms except variants of just using `\\`, then it just keeps on loading (see image below). Not sure if this is something we should care about though since users probably won't be affected negatively by this.
This is made by purpose since I have removed the backslash before passing the search term to the API and moreover, the length of cleaned search term is used when validating for the minimal length (=2). In that case, the GemSearch is waiting for a valid input with at least two characters after input of `\\`. 

I have also tried by not removing `\`, in that case, the escaped search term will be passed to the search API and one actually got hit after typing in `\\` which I think is weird. 

Nevertheless, I don't think any real user will type in `\\` in the search bar. For people who want to break the website, removing `\` is enough. 

I do think we should not overdo things and spend much time on things users might not pay an attention.

**Comment by e0** [comment]
@nanjiangshu Quick follow up. If we do move the sanitizing logic to the backend again and you want to add some tests, you can continue working in [this file](https://github.com/MetabolicAtlas/MetabolicAtlas/blob/develop/api/test/search.test.js). I also find the [Jest documentation](https://jestjs.io/docs/using-matchers) useful to have open when writing tests.

**Comment by nanjiangshu** [comment]
> @nanjiangshu Quick follow up. If we do move the sanitizing logic to the backend again and you want to add some tests, you can continue working in [this file](https://github.com/MetabolicAtlas/MetabolicAtlas/blob/develop/api/test/search.test.js). I also find the [Jest documentation](https://jestjs.io/docs/using-matchers) useful to have open when writing tests.

Great idea to add a test for this API!
We can not simply move the sanitizing logic to the API, it is needed also in the frontend. 
Firstly, the [RegExp of searchTerm](https://github.com/MetabolicAtlas/MetabolicAtlas/blob/81f209a2d7431c65b171cfb8c49a44f930c4f073/frontend/src/components/explorer/gemBrowser/GemSearch.vue#L245) will report an error by vuejs with `invalid syntax` if some special letters (e.g. `(`)are not escaped. This error was not reported by vuejs previously because the `unknowError` was triggered.
Secondly, the [minimal length checking](https://github.com/MetabolicAtlas/MetabolicAtlas/blob/81f209a2d7431c65b171cfb8c49a44f930c4f073/frontend/src/components/explorer/gemBrowser/GemSearch.vue#L207) needs to check the length of the filtered string.

A good solution would be if this function can be used at both the `api` and the `frontend` and a quick and dirty solution would be we define the function at both places.

**Comment by inghylt** [comment]
We should aim to solve #686 and #884 with this issue as well

**Comment by nanjiangshu** [comment]
I think the issue #686 will be solved by the PR #886

**Comment by nanjiangshu** [comment]
I checked with the term @inghylt mentioned in the issue #884 and it is highlighted. 
Could you please verify that the issue #884 is actually solved by this PR?

File: api/src/neo4j/queries/search.js (hunk 1 above)
Comment (nanjiangshu) [reply api/src/neo4j/queries/search.js]: Special treatment with `EC:` is not needed anymore since the symbol `:` is already sanitized. I have removed the both the code and this comment in the commit a9a85114

**Review by MalinAhlberg — APPROVED** [review]
Apart from the complaint from Prettier, I think this looks good! #884 seems to be solved by this too, as you mention.
Good job :+1: !

File: api/test/search.test.js [hunk 2]
```diff
@@ -43,4 +43,23 @@ describe('search', () => {
...
+        model: 'HumanGem',
+        version: HUMAN_GEM_VERSION,
+      }),
+    ]);
+    for (const data of [data1, data2]) {
+      const { name } = data['Human-GEM'];
+      expect(name).toEqual('Human-GEM');
+    }
+  });
+});
```
Comment (inghylt) [inline api/test/search.test.js:65]: Add newline?

Comment (nanjiangshu) [reply api/test/search.test.js:65]: Not quite sure. It's not added in the rest of testing js files.

File: api/src/utils/utils.js [hunk 3]
```diff
@@ -0,0 +1,10 @@
+export function sanitizeSearchString(term, isAddBackSlash = true) {
```
[the remark this answers is not in the document]
Comment (nanjiangshu) [reply api/src/utils/utils.js:1]: When checking for the minimal length of the input string, the backslash should not be added, otherwise, backslashes will also be counted.

File: api/test/search.test.js (hunk 2 above)
Comment (inghylt) [reply api/test/search.test.js]: `ma-exec api yarn format` does react to this as well so I think it makes sense to add it

Comment (nanjiangshu) [reply api/test/search.test.js]: It seems there is a prettier issue as @MalinAhlberg also pointed out. I guess this is caused when I solving the merging conflict in the browser, which ignored the prettier.

File: api/src/utils/utils.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (inghylt) [reply api/src/utils/utils.js:1]: Maybe worth adding a comment about that in GemSearch.vue, but since no one else has asked about it might be superfluous. Up to you :)

**Review by inghylt — APPROVED** [review]
Really nice work!

File: api/src/utils/utils.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (nanjiangshu) [reply api/src/utils/utils.js:1]: Added a comment in c5b7f090

**Comment by nanjiangshu** [comment]
Hi @e0, do you have any other comments for this issue?

**Comment by e0** [comment]
> Hi @e0, do you have any other comments for this issue?

Hi, sorry I didn't mention but since it already got two approvals I didn't take another look. It worked well originally and I trust that your work along with the two approvals are good enough.

**Comment by nanjiangshu** [comment]
Thinking about the actual amount of effort spent on this issue, I would bump it to at least 4.
