### PR TITLE
fix: make sure that the PostgreSQL password is reset after deployment

### LINKED ISSUE #1041: deploying with different PostgreSQL password does not work
**Describe the bug**

Since the `pg` data is persisted, deploying with a different password than what's already set does not work.

**Steps to reproduce**

`deploy-stack dev`

**Expected behavior**

- [ ] Deploying, for example `deploy-stack dev`, should work even if `POSTGRES_PASSWORD` is changed from what's been set before.

### PR DESCRIPTION
**Pull request by e0**
**Related issue(s) and PR(s)**  
This PR closes #1041 and is related to #1023.

**Type of change**  

- [x] Bug fix (non-breaking change which fixes an issue)
 
**List of changes made**  

Adds a command to the `deploy-stack` function that makes sure the password specified in the given `*.env` file is set.

**Testing**  

- A rebuild is needed due to new dependencies
- Instructions on how to test
1. Change the value of `POSTGRES_PASSWORD` in your `env-dev.env` file to something else.
2. Deploy to the dev server `deploy-stack dev`.
3. Verify that the `GotEnzymes` pages are working. For example `/gotenzymes/reaction/R01234`.

**Further comments**  

The way things are setup now. The command to set the password runs after the command to deploy the stack. For this to happen the `pg` container must be up and running before the password command is run. This doesn't seem to be problem since the `ftp` container takes a while to setup properly and the `pg` container sets up before that. Maybe something good to keep in mind though.

**Definition of Done checklist**  
- [x] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] Tests and lint/format validations are passing
- [x] My changes generate no new warnings

### CODE REVIEW

File: proj.sh [hunk 1]
```diff
@@ -49,6 +49,7 @@ function deploy-stack {
   CHOSEN_ENV="env-${1:-$LOCALENV}.env"
   generate-data
   docker compose --env-file $CHOSEN_ENV -f docker-compose.yml -f docker-compose-remote.yml --project-name metabolicatlas up --detach --build --force-recreate --remove-orphans --renew-anon-volumes
+  docker compose --env-file $CHOSEN_ENV -f docker-compose.yml -f docker-compose-remote.yml exec -it pg psql -U postgres -c "alter user postgres with password '${POSTGRES_PASSWORD}';"
```
Comment (mihai-sysbio) [inline proj.sh:52]: This tends to print the output `ALTER ROLE`, which I don't find that informative, so I'm suggesting to hide it with a change in options:
```suggestion
  docker compose --env-file $CHOSEN_ENV -f docker-compose.yml -f docker-compose-remote.yml exec -d pg psql -U postgres -c "alter user postgres with password '${POSTGRES_PASSWORD}';"
```

**Review by mihai-sysbio — APPROVED** [review]
Works great!

**Review by MalinAhlberg — APPROVED** [review]
Nice!

I need the proposal from Mihail (the `-d` flag) for this to work on my machine.

**Comment by e0** [comment]
> Nice!
> 
> I need the proposal from Mihail (the `-d` flag) for this to work on my machine.

Thanks! That also helps confirm the suggestion. I think we can merge this then.
