### PR TITLE
fix: model search bug

### LINKED ISSUE #936: Can't search by metabolite id
- When searching for metabolite id MAM02040c in the search bar of metabolic atlas with "Human-GEM" selected at the left gives no results, but it works fine when using reaction ids or the name of the metabolite (h2o).
Capture_a
Capture_b
Capture_c
Capture_d

- Also, the compartment 's' in the metabolic atlas seems to be different from the external compartment in models, which is 'e'

### PR DESCRIPTION
**Pull request by inghylt**
**Related issue(s) and PR(s)**  
This PR closes #936 and was written by @e0 and @inghylt 

**Type of change**  

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Other, refactoring to make to code more readable and thus less bug prone 
 
**List of changes made**  

- Resolved bug related to UNWIND with empty list. These changes are also made in global search
- Made sure that it is not the lowest scores that is saved if multiple nodes with the same id are in the fulltext search results + refactored the related code to make it more readable to avoid future bugs. These changes are also made in global search.
- Removed redundant code from the search store. Some of it was actually redundant before the changes introduced by this PR, but the main thing is that the API now always returns a score, i.e. there should be no `undefined` cases.

**Screenshot of the fix**  

image

**Testing**  

Search for `MAM02040c` but also other component ids and models

**Further comments**  

An unexpected discovery was made during the bug fixing. Apparently, there are sometimes duplicate components returned from the fulltext search, and the one that appears latest, i.e. the one with the lowest score, will be the one "stored". This is probably the reason behind the situations we have seen in the past with weird scores. 

**Definition of Done checklist**  
- [x] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] Tests and lint/format validations are passing
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by e0 — APPROVED** [review]
LGTM!

**Review by mihai-sysbio — APPROVED** [review]
That was quick @inghylt, nice! Looks good as far as I can tell.
- Did you notice any difference in performance?
- Does this PR also solve #896? edit: Not quite, from what I testef.

**Review by nanjiangshu — APPROVED** [review]
Great fix! I haven't experienced any performance downgrade although no benchmark has been done.

**Comment by inghylt** [comment]
```
const idsToScore = {};
  const uniqueIds = results.reduce((o, r) => {
    const c = intersect(COMPONENT_TYPES, r.labels);
    if (!o[c]) {
      o[c] = new Set();
    }
    o[c].add(r.id);
    idsToScore[r.id] = r.score;
    // Sometimes there are duplicate components with different score, and the lower score
    // will then override the higher score without this if statement
    if (!idsToScore[r.id]) {
      o[c].add(r.id);
      idsToScore[r.id] = r.score;
    }
    return o;
  }, {});
```

I feel like this code can be rewritten. It's kind of messy and we are using Set but still have to make a check if r.id is present. Should I create a new issue for it? Or try to make it better in this PR?

**Comment by mihai-sysbio** [comment]
> Should I create a new issue for it? Or try to make it better in this PR?

This branch has been deployed so there is no time-pressure anymore, if you feel like it makes sense to continue in this PR.

**Comment by inghylt** [comment]
Pushed the changes I sat with a bit last week. I think the code was a bit messy and hard to understand (thus more bug prone) before, hope you guys think this is an improvement as well. @MalinAhlberg I realized now as well why some scores was undefined in #887, see the commit message dc44435. If you guys approve these changes, we could create an issue (or fix here directly) to remove the check at https://github.com/MetabolicAtlas/MetabolicAtlas/blob/f780f4b597bbf01c1721577c94a26802152fdb17/frontend/src/store/modules/search.js#L25

**Comment by inghylt** [comment]
Just noticed now, the bugs fixed in this PR is still present in global search. Should we fix global search as well in this PR?

**Review by e0 — APPROVED** [review]
Good job on the new refactoring! I think it's more appropriate that we are using `for` loops now instead of using `reduce` and it's more readable.

Regarding global search, the bug is not as severe since the result is still included but ranked lower. I feel a bit conflicted about whether to fix it now or not. We mentioned before that we would like to tackle the global search pagination/redesign issue _soon_, which means that in the mean time it could require more time whenever we are fixing anything related to the search logic. What do you think?

**Comment by MalinAhlberg** [comment]
> Pushed the changes I sat with a bit last week. I think the code was a bit messy and hard to understand (thus more bug prone) before, hope you guys think this is an improvement as well. @MalinAhlberg I realized now as well why some scores was undefined in #887, see the commit message [dc44435](https://github.com/MetabolicAtlas/MetabolicAtlas/commit/dc4443508adc676276322191d15b16e5a11bf565). If you guys approve these changes, we could create an issue (or fix here directly) to remove this check
> 

Nice, the `undefined`s actually seem to be gone :v:. I really like the refactoring too!
I vote for removing the line you mentioned above, and fixing the issue in global search before we re-test and merge this.

**Review by nanjiangshu — APPROVED** [review]
Really nice fix and refactoring. I feel the new code much easier to understand and better in dealing with duplicated IDs in the result result. 

1. For the global search, I agree with @e0 that the bug is less critical and I would vote for being solved in a separate issue. Mabye together with the major re-writing of the global search function. 
2. For checking `undefined`, it think it's more logical to define it in the API than to check it in the frontend. Strictly speaking, this line 
```javascript
score: obj.id in uniqueIds ? uniqueIds[obj.id]['score'] : 0,
```
may still result in an undefined score if `uniqueIds[obj.id]['score']` is undefined. But I guess this won't happen, otherwise it will be a bug with neo4j 😃

File: api/src/neo4j/queries/search/globalSearch.js [hunk 1]
```diff
@@ -18,14 +18,22 @@ const fetchCompartmentalizedMetabolites = async ({
...
 `;
   } else {
     statement += `
 WITH ${JSON.stringify(ids)} as cmids
-UNWIND cmids as cmid
+UNWIND
+  CASE
+      WHEN cmids = [] THEN [null]
+      ELSE cmids
+  END AS cmid
```
Comment (e0) [inline api/src/neo4j/queries/search/globalSearch.js:36]: Did this cause any problems specifically for the global search? Just curious since it seemed like it wasn't needed for the model search.

**Comment by inghylt** [comment]
(Hopefully) Final re-request! I have now removed the unnecessary if undefined statement and applied the fixes to global search as well. See the updated PR description and commits for more information.

Btw @nanjiangshu I tried out the examples in [this comment](https://github.com/MetabolicAtlas/MetabolicAtlas/pull/938#pullrequestreview-925858090) and they all seem to work well

File: frontend/src/store/modules/search.js [hunk 2]
```diff
@@ -21,16 +21,11 @@ const categorizeResults = results => {
...
-              d.score = 0;
-            }
             if (e.score > categoryScore || !categoryScore) {
               categoryScore = e.score;
             }
-            categoryScore = e.score > categoryScore ? e.score : categoryScore;
-            d.model = { id: model, name: resultsModel.name };
-            return d;
+            e.model = { id: model, name: resultsModel.name };
+            return e;
```
Comment (e0) [inline frontend/src/store/modules/search.js:28]: While we do not have [this eslint rule](https://eslint.org/docs/rules/no-param-reassign) in place, it is considered good practice to not mutate function params in JavaScript. In this case I think the following should amount to the same value without mutating the function param.

```suggestion
            return { ...e, model: { id: model, name: resultsModel.name } };
```

**Review by e0 — APPROVED** [review]
Looks great! Nice that you took time to fix the global search as well. I left a couple of minor comments but they do not necessarily need to be addressed imo so approving this now.

File: api/src/neo4j/queries/search/globalSearch.js (hunk 1 above)
Comment (inghylt) [reply api/src/neo4j/queries/search/globalSearch.js:36]: There was no error what I noticed in global search, but it felt safer to add this if (c)mids would be empty for some query.

Comment (inghylt) [reply api/src/neo4j/queries/search/globalSearch.js:36]: I don't think we tested anything in global search? Either way, I also agree it makes sense to keep it as is for now

Comment (e0) [reply api/src/neo4j/queries/search/globalSearch.js:36]: You are right! I assumed that it would work the same way.

**Review by MalinAhlberg — APPROVED** [review]
Good work!

**Comment by nanjiangshu** [comment]
> (Hopefully) Final re-request! I have now removed the unnecessary if undefined statement and applied the fixes to global search as well. See the updated PR description and commits for more information.
> 
> Btw @nanjiangshu I tried out the examples in [this comment](https://github.com/MetabolicAtlas/MetabolicAtlas/pull/938#pullrequestreview-925858090) and they all seem to work well

Yes. That comment is resolved. See the slack discussion at https://nbisweden.slack.com/archives/C01D13EKUV7/p1648642859897109

**Review by nanjiangshu — APPROVED** [review]
LGTM!
